export const PermissionCode = {
  // Companies
  VIEW_COMPANIES: 'VIEW_COMPANIES',
  CREATE_COMPANIES: 'CREATE_COMPANIES',
  UPDATE_COMPANIES: 'UPDATE_COMPANIES',
  DELETE_COMPANIES: 'DELETE_COMPANIES',

  // Headquarters
  VIEW_HEADQUARTERS: 'VIEW_HEADQUARTERS',
  CREATE_HEADQUARTERS: 'CREATE_HEADQUARTERS',
  UPDATE_HEADQUARTERS: 'UPDATE_HEADQUARTERS',
  DELETE_HEADQUARTERS: 'DELETE_HEADQUARTERS',

  // Users
  VIEW_USERS: 'VIEW_USERS',
  CREATE_USERS: 'CREATE_USERS',
  UPDATE_USERS: 'UPDATE_USERS',
  DELETE_USERS: 'DELETE_USERS',

  // Roles & Permissions
  VIEW_ROLES: 'VIEW_ROLES',
  MANAGE_ROLES: 'MANAGE_ROLES',
  VIEW_PERMISSIONS: 'VIEW_PERMISSIONS',

  // Carbon Footprint
  VIEW_CARBON_FOOTPRINT: 'VIEW_CARBON_FOOTPRINT',
  CREATE_CARBON_FOOTPRINT: 'CREATE_CARBON_FOOTPRINT',
  DELETE_CARBON_FOOTPRINT: 'DELETE_CARBON_FOOTPRINT',
  VIEW_CARBON_FOOTPRINT_ANALYSIS: 'VIEW_CARBON_FOOTPRINT_ANALYSIS',
  MANAGE_EMISSION_FACTORS: 'MANAGE_EMISSION_FACTORS',
} as const;

export type PermissionCodeType = (typeof PermissionCode)[keyof typeof PermissionCode];
